defaults:
  - dataset: udem-birds 
project_name: Test Paper
run_name: Test run
tags: 
  - 'debug'


num_workers: 4
nb_epochs: 100000
batch_size: 2
lr: 0.00002
latent_loss_weight: 0.25
net:
  in_channel: 1

debug: True