dataset:
  num_workers: 6
  root_dir: '/media/future/Rapido/NIPS4B_BIRD_CHALLENGE_TRAIN_TEST_WAV/birds-generation-classification/'
  train_path: '${dataset.root_dir}/train.txt'
  val_path: '${dataset.root_dir}/test.txt'
  test_path: '${dataset.root_dir}/test.txt'
  lmdb_path: ''

  batch_size: 32
  classes_name: 
      - Aegcau_call
      - Butbut_call
      - Cerbra_call
      - Denmaj_call
      - Embcir_call
      - Erirub_call
      - Fricoe_call
      - Galcri_call
      - Lopcri_call
      - Loxcur_call
      - Lusmeg_call
      - Parate_call
      - Parmaj_call
      - Pelgra_call
      - Petpet_call
      - Picpic_call
      - Poepal_call
      - Regign_call
      - Sylund_call
      - Turmer_call

  transforms: ''
  resize: false
  return_tuple: true
  return_tuple_of3: true
  sr: 22050
  use_mel: true
  use_cache: false
  use_rgb: true
