dataset:
  num_workers: 6
  root_dir: '/media/future/Rapido/NIPS4B_BIRD_CHALLENGE_TRAIN_TEST_WAV/birds-generation-classification/'
  train_path: '${dataset.root_dir}/train.txt'
  val_path: '${dataset.root_dir}/test.txt'
  test_path: '${dataset.root_dir}/test.txt'
  lmdb_path: ''

  batch_size: 32
  classes_name: 
      - Cisjun_song
      - Colpal_song
      - Embcir_song
      - Fricoe_song
      - Galcri_song
      - Oriori_song
      - Petpet_song
      - Phofem_song
      - Phycol_song
      - Poepal_song
      - Prumod_song
      - Serser_song
      - Siteur_song
      - Strdec_song
      - Strtur_song
      - Sylatr_song
      - Tetpyg_song

  transforms: ''
  resize: false
  return_tuple: true
  return_tuple_of3: true
  sr: 22050
  use_mel: true
  use_cache: false
  use_rgb: true
