dataset:
  num_workers: 6
  root_dir: '/media/future/Rapido/NIPS4B_BIRD_CHALLENGE_TRAIN_TEST_WAV/birds-generation-classification/'
  train_path: '${dataset.root_dir}/train.txt'
  val_path: '${dataset.root_dir}/test.txt'
  test_path: '${dataset.root_dir}/test.txt'
  lmdb_path: ''

  batch_size: 6
  classes_name: 
      - Aegcau_call
      - Alaarv_song
      - Anttri_song
      - Butbut_call
      - Carcan_call
      - Carcan_song
      - Carcar_call
      - Carcar_song
      - Cerbra_call
      - Cerbra_song
      - Cetcet_song
      - Chlchl_call
      - Cicatr_song
      - Cicorn_song
      - Cisjun_song
      - Colpal_song
      - Corcor_call
      - Denmaj_call
      - Denmaj_drum
      - Embcir_call
      - Embcir_song
      - Erirub_call
      - Erirub_song
      - Fricoe_call
      - Fricoe_song
      - Galcri_call
      - Galcri_song
      - Galthe_call
      - Galthe_song
      - Gargla_call
      - Hirrus_call
      - Jyntor_song
      - Lopcri_call
      - Loxcur_call
      - Lularb_song
      - Lusmeg_call
      - Lusmeg_song
      - Lyrple_song
      - Motcin_call
      - Musstr_call
      - Oriori_call
      - Oriori_song
      - Parate_call
      - Parate_song
      - Parcae_call
      - Parcae_song
      - Parmaj_call
      - Parmaj_song
      - Pasdom_call
      - Pelgra_call
      - Petpet_call
      - Petpet_song
      - Phofem_song
      - Phycol_call
      - Phycol_song
      - Picpic_call
      - Plaaff_song
      - Plasab_song
      - Poepal_call
      - Poepal_song
      - Prumod_song
      - Ptehey_song
      - Pyrpyr_call
      - Regign_call
      - Regign_song
      - Serser_call
      - Serser_song
      - Siteur_call
      - Siteur_song
      - Strdec_song
      - Strtur_song
      - Stuvul_call
      - Sylatr_call
      - Sylatr_song
      - Sylcan_call
      - Sylcan_song
      - Sylmel_call
      - Sylmel_song
      - Sylund_call
      - Sylund_song
      - Tetpyg_song
      - Tibtom_song
      - Trotro_song
      - Turmer_call
      - Turmer_song
      - Turphi_call
      - Turphi_song

  resize: false
  return_tuple: true
  return_tuple_of3: true
  sr: 22050
  use_mel: true
  use_cache: false
  use_rgb: true
