dataset:
  num_workers: 6
  root_dir: '/media/future/Rapido/NIPS4B_BIRD_CHALLENGE_TRAIN_TEST_WAV/birds-generation-classification/'
  train_path: '${dataset.root_dir}/train.txt'
  val_path: '${dataset.root_dir}/test.txt'
  test_path: '${dataset.root_dir}/test.txt'
  lmdb_path: ''

  batch_size: 32
  classes_name: 
      - Carcan_song
      - Carcar_song
      - Cerbra_song
      - Denmaj_drum
      - Embcir_song
      - Erirub_song
      - Fricoe_song
      - Galcri_song
      - Galthe_song
      - Lusmeg_song
      - Oriori_song
      - Parate_song
      - Parcae_song
      - Parmaj_song
      - Petpet_song
      - Phycol_song
      - Poepal_song
      - Regign_song
      - Serser_song
      - Siteur_song
      - Sylatr_song
      - Sylcan_song
      - Sylmel_song
      - Sylund_song
      - Turmer_song
      - Turphi_song

  transforms: ''
  resize: false
  return_tuple: true
  return_tuple_of3: true
  sr: 22050
  use_mel: true
  use_cache: false
  use_rgb: true
